apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{app_name}}-deployment
  labels:
    app: {{app_name}}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{app_name}}
  template:
    metadata:
      labels:
        app: {{app_name}}
    spec:
      containers:
      - name: {{app_name}}
        image: {{aws_user_name}}.dkr.ecr.ap-northeast-1.amazonaws.com/{{image_name}}:{{image_tag}}
